### ISSUE TITLE
Simulation terminated abnormally

### ISSUE THREAD

**Issue by nrc53** [Systems-ShiftLab/MultiPIM#1]
While running example simulation on MultiPIM (as per the instructions in github repo), I am getting a run time error as below. Can you please help me with fixing it. 

nrc53@LAPTOP-3NAV9DC1:~/MultiPIM/tests$ ./run_pim.sh
[H] Starting MultiPIM 2021-03-25 09:11:58, built 2021-03-17 14:46:54 (rev )
[H] Harness PID 177
[H] Creating global segment, 2048 MBs
[H] Global segment shmid = 1
[H] Deadlock detection ON
[H] Using env path /home/nrc53/MultiPIM
[H] Pin cmd for process 0:
/home/nrc53/MultiPIM/pin/intel64/bin/pinbin -injection child -follow_execv -tool_exit_timeout 1 -ifeellucky -t /home/nrc53/MultiPIM/build/opt/libzsim.so -config /home/nrc53/MultiPIM/tests/pim.cfg -procConfig /home/nrc53/MultiPIM/tests/cmd.cfg -outputDir /home/nrc53/MultiPIM/tests/output -shmid 1 -harnessPid 177 -procIdx 0 -- ./benchmarks/Polybench/linear-algebra/kernels/atax/atax
[S 0] Started instance
[S 0] Started RR scheduler, quantum=100 phases
[S 0] Using env path /home/nrc53/MultiPIM
[S 0] Paging mode: LongMode_Normal
[S 0] Cache prefix: sys.caches.l2.
[S 0] Cache prefix: sys.caches.l1i.
[S 0] Cache prefix: sys.caches.l1d.
Pin app terminated abnormally due to signal 11.
[H] Child 178 done
[H] All children done, exiting

Please let me know if you need any more details. I am running the simulation on Ubuntu 20.04. I installed all the latest versions of the dependencies.

**Comment by yuchaocs** [comment]
Did you try the simulator on Ubuntu 18.04 or older version environments?

**Comment by nrc53** [comment]
I have not, can you please provide a list of dependencies along with the version numbers or else a docker image? 

Thanks,
Naga.

**Comment by yuchaocs** [comment]
Sure. We will provide a docker image later.

**Comment by nrc53** [comment]
I could run the simulation in Ubuntu 18.04. 

Thanks.

**Comment by anuragkar09** [comment]
Hi, I tried running the simulation on Ubuntu 18.04.6 and it still failed. I know this thread is closed - but I have the exact same issue. Could someone help resolve this?

**Comment by satanu01** [comment]
I'm also getting the same issue on Ubuntu 18.
