### ISSUE TITLE
PIM-only simulation and the PIM Interface

### ISSUE THREAD

**Issue by LiZerun** [Systems-ShiftLab/MultiPIM#2]
Hi, I mainly have the following questions:
1. I noticed that the current version doesn't support CPU-PIM co-simulation and there are two kinds of PIM-task interface. So, when I run a PIM-only simulation task, does the traces.out file only contain the simulation result of the code declared by the PIM-task interfaces, or the simulation result of the entire code?

2. I learned from the paper that PIMCore is based on ZSim's Timing Core, and other types of Core can be used. How do I use the PIMCore based on Simple Core?(It seems that the speed of the simulation based the default core is a bit slow)

3. Does MultiPIM support single HMC simulation? If so, how can I do it?(I tried to modify the sys.mem.ramulatorConfig to "DDR-config.cfg", but it could not run successfully)

I have only recently started to learn about simulators, some questions may be naive, I hope you don't mind.

**Comment by LiZerun** [comment]
When I was trying to simulate single-HMC, I ran into the following problem:

In addition to the parameters you mentioned, I also tried to modify : 
"**stacks = 1**" in MultiPIM-hmc-*.cfg file,  
**sys.sim.parallelism=32**.

Below is my topology.xml file:
`<!DOCTYPE memtopology SYSTEM "memtopology.dtd">
<memtopology>
  <memnodes num="1" linkspernode="4">
    <node id="0">
        <link id="0" tocpu="true" />
        <link id="1" tocpu="true" />
        <link id="2" tocpu="true" />
        <link id="3" tocpu="true" />
    </node>
  </memnodes>

  <meminterconnections>
  </meminterconnections>

  <memroutes type="static">
    <cpuroute dst="0" next="0"/>
  </memroutes>
</memtopology>
`

The Dump Trace is below:
[S 0] [OFFLOAD_MP_BEGIN], entering offload MP region
Invalid index 2, size 2
Dump Trace:
0: _Z10Dump_Tracev
/home/lizerun/Algoirthm/MultiPIM/build/opt/debug_zsim.cpp:131
1: _ZN5Stats10VectorBaseINS_6VectorENS_6ScalarEEixEj
/home/lizerun/Algoirthm/MultiPIM/build/opt/ramulator/StatType.h:372
2: _ZN9ramulator6MemoryINS_3HMCENS_10ControllerEE15stat_mem_accessERNS_7RequestE.constprop.1022
/home/lizerun/Algoirthm/MultiPIM/build/opt/ramulator/StatType.h:241
3: _ZN9ramulator6MemoryINS_3HMCENS_10ControllerEE19pu_receive_requestsERNS_7RequestE
/usr/include/c++/7/bits/std_function.h:704
4: _ZN9ramulator6SwitchINS_3HMCEE11vault_ejectERSt3setIiSt4lessIiESaIiEE
/home/lizerun/Algoirthm/MultiPIM/build/opt/ramulator/HMC_Controller.h:799
5: _ZN9ramulator6SwitchINS_3HMCEE4tickEv
/home/lizerun/Algoirthm/MultiPIM/build/opt/ramulator/LogicLayer.cpp:553
6: _ZN9ramulator6MemoryINS_3HMCENS_10ControllerEE4tickEv
/home/lizerun/Algoirthm/MultiPIM/build/opt/ramulator/HMC_Memory.h:1005
7: _ZN9ramulator11ZsimWrapper4tickEm
/home/lizerun/Algoirthm/MultiPIM/build/opt/ramulator/ZsimWrapper.cpp:95
8: _ZN15RamulatorMemory4tickEm
/home/lizerun/Algoirthm/MultiPIM/build/opt/ramulator_mem_ctrl.cpp:267
9: _ZN9TickEventI15RamulatorMemoryE8simulateEm
/home/lizerun/Algoirthm/MultiPIM/build/opt/tick_event.h:57
10: _ZN13ContentionSim19simulatePhaseThreadEj
/home/lizerun/Algoirthm/MultiPIM/build/opt/contention_sim.cpp:328
11: _ZN13ContentionSim13simThreadLoopEj
/home/lizerun/Algoirthm/MultiPIM/build/opt/contention_sim.cpp:301
12: ??
??:0
13: ??
??:0
pinbin: build/opt/ramulator/StatType.h:374: Element& Stats::VectorBase<Derived, Element>::operator[](Stats::off_type) [with Derived = Stats::Vector; Element = Stats::Scalar; Stats::off_type = unsigned int]: Assertion `index >= 0 && index < size()' failed.
Pin app terminated abnormally due to signal 6.
[H] Child 6527 done
[H] Panic on build/opt/zsim_harness.cpp:123: Child 6527 (idx 0) exit was anomalous, killing simulation

**Comment by yuchaocs** [comment]
I will create a config for single HMC later.
