### ISSUE TITLE
Output die not exists! Bad address

### ISSUE THREAD

**Issue by Shubhang-Pandey** [Systems-ShiftLab/MultiPIM#3]
I am new to MultiPIM and have followed the instructions. But after ./run_pim.sh, I am constantly getting the bad address in the output. Please guide me through if I am missing a step.

[H] Starting MultiPIM 2021-05-11 23:02:35, built 2021-05-11 21:42:02 (rev 1.0)
[H] Harness PID 31021
Output dir not exist!
: Bad address

**Comment by yuchaocs** [comment]
Look at the script, you need to create an "output" dir.
