### ISSUE TITLE
library not found during compilation 

### ISSUE THREAD

**Issue by jh2vs** [Systems-ShiftLab/MultiPIM#4]
Hello, I'm new to MultiPIM and trying to install it on our server. I got this error during compilation. 

 -lcurl -lhdf5 -lhdf5_hl
/usr/bin/ld: cannot find -lboost_program_options
collect2: error: ld returned 1 exit status
scons: *** [build/opt/libzsim.so] Error 1
scons: building terminated because of errors.

**Comment by yuchaocs** [comment]
Did you execute the "setup.sh" script?

**Comment by jh2vs** [comment]
Yes, the system administrator completed the setup script together.

**Comment by yuchaocs** [comment]
If the boost_program_options lib cannot be found, you need to install it.

**Comment by jh2vs** [comment]
I apologize if I'm asking stupid questions.
Can you specify the install package? We didn't get any issues during the setup.sh script.

**Comment by yuchaocs** [comment]
The package name is "boost_program_options", however, different linux OSs may have different names.

Or you can just install the "boost" library.

**Comment by jh2vs** [comment]
Thanks a lot!
