### ISSUE TITLE
Error after trying to script XML file for mesh topology.

### ISSUE THREAD

**Issue by Shubhang-Pandey** [Systems-ShiftLab/MultiPIM#5]
Please help with the issue
pinbin: build/opt/ramulator/MemTopoParser.cpp:116: virtual void ramulator::MemTopoParser::startElement(const string&, const xercesc_3_2::Attributes&): Assertion `next >=src*memoryTopology.linkspernode && next < ((src+1)*memoryTopology.linkspernode)' failed.

**Comment by Shubhang-Pandey** [comment]
Awaiting your response.

**Comment by yuchaocs** [comment]
When a memory node sends a packet, the next port is one of the ports of the memory node. Please check whether you route rules satisfy the above rule or not.

**Comment by Shubhang-Pandey** [comment]
Thanks I was able to figure it out
