### ISSUE TITLE
Calculate the final IPC or final time

### ISSUE THREAD

**Issue by HSoulZ** [Systems-ShiftLab/MultiPIM#6]
Hello, I run the PIM task and I wonder how to calculate the final IPC or final time.

1. I count the instrcutions and cycles from traces.out.zsim-ev.h5. Assume they are A and B respectively. 
2. I can just find dram_cycles and incoming_requests in ramulator.status. Assume they are C and D respectively. 
3. What should do to calculate the final performance? B * cpu_cycle_time + C * memory_cycle_time?

Thanks, 
Hannah.

**Comment by yuchaocs** [comment]
Actually, the cycles extracted from traces.out.zsim-ev.h5 already considers the cycles of memory.

To calculate the final IPC, first get the final number of instructions (totalInstrs) executed by all cores. For the system cycles, MultiPIM maintains a global cycle for PIM cores. You can get PIM cores' cycle (pimCycles) from Heartbeat.totalCycle. 

Final IPC = (1.*totalInstrs)/pimCycles
