### ISSUE TITLE
Support for the following error

### ISSUE THREAD

**Issue by Shubhang-Pandey** [Systems-ShiftLab/MultiPIM#7]
[S 0] [OFFLOAD_MP_BEGIN], entering offload MP region
pinbin: build/opt/ramulator/LogicLayer.cpp:269: void ramulator::Switch<T>::vault_inject(std::set<int>&) [with T = ramulator::HMC]: Assertion `route_link->type != Link<T>::Type::HOST_SOURCE_MODE' failed.
Pin app terminated abnormally due to signal 6.
[H] Child 23165 done
[H] Panic on build/opt/zsim_harness.cpp:123: Child 23165 (idx 0) exit was anomalous, killing simulation

This error is persistent with all topologies I am trying to configure. Kindly tell me what is the possible reason for the error.
 It would be really helpful if you give another example for configuration such as one available for dragonfly topology.

**Comment by yuchaocs** [comment]
There may be something wrong with your route rules. 
Show one of your topologies.

**Comment by Shubhang-Pandey** [comment]
Following is the mesh topology prepared with 16 mem units under the constraints of 4links
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<memtopology>
<memnodes num="16" linkspernode="4">
<node id="0">
<link id="0" tocpu="true"/>
<link id="1" tocpu="false"/>
<link id="2" tocpu="false"/>
<link id="3" tocpu="false"/>
</node>
<node id="1">
<link id="4" tocpu="false"/>
<link id="5" tocpu="false"/>
<link id="6" tocpu="false"/>
<link id="7" tocpu="false"/>
</node>
<node id="2">
<link id="8" tocpu="false"/>
<link id="9" tocpu="false"/>
<link id="10" tocpu="false"/>
<link id="11" tocpu="false"/>
</node>
<node id="3">
<link id="12" tocpu="false"/>
<link id="13" tocpu="true"/>
<link id="14" tocpu="false"/>
<link id="15" tocpu="false"/>
</node>
<node id="4">
<link id="16" tocpu="false"/>
<link id="17" tocpu="false"/>
<link id="18" tocpu="false"/>
<link id="19" tocpu="false"/>
</node>
<node id="5">
<link id="20" tocpu="false"/>
<link id="21" tocpu="false"/>
<link id="22" tocpu="false"/>
<link id="23" tocpu="false"/>
</node>
<node id="6">
<link id="24" tocpu="false"/>
<link id="25" tocpu="false"/>
<link id="26" tocpu="false"/>
<link id="27" tocpu="false"/>
</node>
<node id="7">
<link id="28" tocpu="false"/>
<link id="29" tocpu="false"/>
<link id="30" tocpu="false"/>
<link id="31" tocpu="false"/>
</node>
<node id="8">
<link id="32" tocpu="false"/>
<link id="33" tocpu="false"/>
<link id="34" tocpu="false"/>
<link id="35" tocpu="false"/>
</node>
<node id="9">
<link id="36" tocpu="false"/>
<link id="37" tocpu="false"/>
<link id="38" tocpu="false"/>
<link id="39" tocpu="false"/>
</node>
<node id="10">
<link id="40" tocpu="false"/>
<link id="41" tocpu="false"/>
<link id="42" tocpu="false"/>
<link id="43" tocpu="false"/>
</node>
<node id="11">
<link id="44" tocpu="false"/>
<link id="45" tocpu="false"/>
<link id="46" tocpu="false"/>
<link id="47" tocpu="false"/>
</node>
<node id="12">
<link id="48" tocpu="true"/>
<link id="49" tocpu="false"/>
<link id="50" tocpu="false"/>
<link id="51" tocpu="false"/>
</node>
<node id="13">
<link id="52" tocpu="false"/>
<link id="53" tocpu="false"/>
<link id="54" tocpu="false"/>
<link id="55" tocpu="false"/>
</node>
<node id="14">
<link id="56" tocpu="false"/>
<link id="57" tocpu="false"/>
<link id="58" tocpu="false"/>
<link id="59" tocpu="false"/>
</node>
<node id="15">
<link id="60" tocpu="false"/>
<link id="61" tocpu="false"/>
<link id="62" tocpu="false"/>
<link id="63" tocpu="true"/>
</node>
</memnodes>
<meminterconnections>
<interconnection from="1" to="4" type="undirected"/>
<interconnection from="2" to="16" type="undirected"/>
<interconnection from="3" to="17" type="undirected"/>
<interconnection from="5" to="21" type="undirected"/>
<interconnection from="6" to="8" type="undirected"/>
<interconnection from="7" to="9" type="undirected"/>
<interconnection from="10" to="25" type="undirected"/>
<interconnection from="11" to="12" type="undirected"/>
<interconnection from="14" to="29" type="undirected"/>
<interconnection from="15" to="30" type="undirected"/>
<interconnection from="18" to="20" type="undirected"/>
<interconnection from="19" to="32" type="undirected"/>
<interconnection from="22" to="24" type="undirected"/>
<interconnection from="23" to="37" type="undirected"/>
<interconnection from="27" to="41" type="undirected"/>
<interconnection from="26" to="28" type="undirected"/>
<interconnection from="31" to="45" type="undirected"/>
<interconnection from="33" to="36" type="undirected"/>
<interconnection from="38" to="40" type="undirected"/>
<interconnection from="39" to="53" type="undirected"/>
<interconnection from="42" to="44" type="undirected"/>
<interconnection from="43" to="58" type="undirected"/>
<interconnection from="46" to="61" type="undirected"/>
<interconnection from="47" to="62" type="undirected"/>
<interconnection from="34" to="49" type="undirected"/>
<interconnection from="35" to="50" type="undirected"/>
<interconnection from="51" to="52" type="undirected"/>
<interconnection from="54" to="56" type="undirected"/>
<interconnection from="55" to="57" type="undirected"/>
<interconnection from="59" to="60" type="undirected"/>
</meminterconnections>

<memroutes type="static">
<route src="0" dst="1" next="1"/>
<route src="0" dst="2" next="1"/>
<route src="0" dst="3" next="1"/>
<route src="0" dst="4" next="2"/>
<route src="0" dst="5" next="2"/>
<route src="0" dst="6" next="2"/>
<route src="0" dst="7" next="2"/>
<route src="0" dst="8" next="2"/>
<route src="0" dst="9" next="2"/>
<route src="0" dst="10" next="2"/>
<route src="0" dst="11" next="2"/>
<route src="0" dst="12" next="2"/>
<route src="0" dst="13" next="2"/>
<route src="0" dst="14" next="2"/>
<route src="0" dst="15" next="2"/>
<route src="1" dst="0" next="4"/>
<route src="1" dst="2" next="6"/>
<route src="1" dst="3" next="6"/>
<route src="1" dst="4" next="4"/>
<route src="1" dst="5" next="5"/>
<route src="1" dst="6" next="5"/>
<route src="1" dst="7" next="5"/>
<route src="1" dst="8" next="4"/>
<route src="1" dst="9" next="5"/>
<route src="1" dst="10" next="5"/>
<route src="1" dst="11" next="5"/>
<route src="1" dst="12" next="4"/>
<route src="1" dst="13" next="5"/>
<route src="1" dst="14" next="5"/>
<route src="1" dst="15" next="5"/>
<route src="2" dst="0" next="8"/>
<route src="2" dst="1" next="8"/>
<route src="2" dst="3" next="11"/>
<route src="2" dst="4" next="8"/>
<route src="2" dst="5" next="8"/>
<route src="2" dst="6" next="10"/>
<route src="2" dst="7" next="10"/>
<route src="2" dst="8" next="8"/>
<route src="2" dst="9" next="8"/>
<route src="2" dst="10" next="10"/>
<route src="2" dst="11" next="10"/>
<route src="2" dst="12" next="8"/>
<route src="2" dst="13" next="8"/>
<route src="2" dst="14" next="10"/>
<route src="2" dst="15" next="10"/>
<route src="3" dst="0" next="12"/>
<route src="3" dst="1" next="12"/>
<route src="3" dst="2" next="12"/>
<route src="3" dst="4" next="12"/>
<route src="3" dst="5" next="12"/>
<route src="3" dst="6" next="12"/>
<route src="3" dst="7" next="14"/>
<route src="3" dst="8" next="12"/>
<route src="3" dst="9" next="12"/>
<route src="3" dst="10" next="12"/>
<route src="3" dst="11" next="14"/>
<route src="3" dst="12" next="12"/>
<route src="3" dst="13" next="12"/>
<route src="3" dst="14" next="12"/>
<route src="3" dst="15" next="14"/>
<route src="4" dst="0" next="16"/>
<route src="4" dst="1" next="16"/>
<route src="4" dst="2" next="16"/>
<route src="4" dst="3" next="16"/>
<route src="4" dst="5" next="18"/>
<route src="4" dst="6" next="18"/>
<route src="4" dst="7" next="18"/>
<route src="4" dst="8" next="19"/>
<route src="4" dst="9" next="19"/>
<route src="4" dst="10" next="19"/>
<route src="4" dst="11" next="19"/>
<route src="4" dst="12" next="19"/>
<route src="4" dst="13" next="19"/>
<route src="4" dst="14" next="19"/>
<route src="4" dst="15" next="19"/>
<route src="5" dst="0" next="20"/>
<route src="5" dst="1" next="21"/>
<route src="5" dst="2" next="21"/>
<route src="5" dst="3" next="21"/>
<route src="5" dst="4" next="20"/>
<route src="5" dst="6" next="22"/>
<route src="5" dst="7" next="22"/>
<route src="5" dst="8" next="20"/>
<route src="5" dst="9" next="23"/>
<route src="5" dst="10" next="23"/>
<route src="5" dst="11" next="23"/>
<route src="5" dst="12" next="20"/>
<route src="5" dst="13" next="23"/>
<route src="5" dst="14" next="23"/>
<route src="5" dst="15" next="23"/>
<route src="6" dst="0" next="24"/>
<route src="6" dst="1" next="24"/>
<route src="6" dst="2" next="25"/>
<route src="6" dst="3" next="25"/>
<route src="6" dst="4" next="24"/>
<route src="6" dst="5" next="24"/>
<route src="6" dst="7" next="26"/>
<route src="6" dst="8" next="24"/>
<route src="6" dst="9" next="24"/>
<route src="6" dst="10" next="27"/>
<route src="6" dst="11" next="27"/>
<route src="6" dst="12" next="24"/>
<route src="6" dst="13" next="24"/>
<route src="6" dst="14" next="27"/>
<route src="6" dst="15" next="27"/>
<route src="7" dst="0" next="28"/>
<route src="7" dst="1" next="28"/>
<route src="7" dst="2" next="28"/>
<route src="7" dst="3" next="29"/>
<route src="7" dst="4" next="28"/>
<route src="7" dst="5" next="28"/>
<route src="7" dst="6" next="28"/>
<route src="7" dst="8" next="28"/>
<route src="7" dst="9" next="28"/>
<route src="7" dst="10" next="28"/>
<route src="7" dst="11" next="31"/>
<route src="7" dst="12" next="28"/>
<route src="7" dst="13" next="28"/>
<route src="7" dst="14" next="28"/>
<route src="7" dst="15" next="31"/>
<route src="8" dst="0" next="32"/>
<route src="8" dst="1" next="32"/>
<route src="8" dst="2" next="32"/>
<route src="8" dst="3" next="32"/>
<route src="8" dst="4" next="32"/>
<route src="8" dst="5" next="32"/>
<route src="8" dst="6" next="32"/>
<route src="8" dst="7" next="32"/>
<route src="8" dst="9" next="33"/>
<route src="8" dst="10" next="33"/>
<route src="8" dst="11" next="33"/>
<route src="8" dst="12" next="35"/>
<route src="8" dst="13" next="35"/>
<route src="8" dst="14" next="35"/>
<route src="8" dst="15" next="35"/>
<route src="9" dst="0" next="36"/>
<route src="9" dst="1" next="37"/>
<route src="9" dst="2" next="37"/>
<route src="9" dst="3" next="37"/>
<route src="9" dst="4" next="36"/>
<route src="9" dst="5" next="37"/>
<route src="9" dst="6" next="37"/>
<route src="9" dst="7" next="37"/>
<route src="9" dst="8" next="36"/>
<route src="9" dst="10" next="38"/>
<route src="9" dst="11" next="38"/>
<route src="9" dst="12" next="36"/>
<route src="9" dst="13" next="39"/>
<route src="9" dst="14" next="39"/>
<route src="9" dst="15" next="39"/>
<route src="10" dst="0" next="40"/>
<route src="10" dst="1" next="40"/>
<route src="10" dst="2" next="41"/>
<route src="10" dst="3" next="41"/>
<route src="10" dst="4" next="40"/>
<route src="10" dst="5" next="40"/>
<route src="10" dst="6" next="41"/>
<route src="10" dst="7" next="41"/>
<route src="10" dst="8" next="40"/>
<route src="10" dst="9" next="40"/>
<route src="10" dst="11" next="42"/>
<route src="10" dst="12" next="40"/>
<route src="10" dst="13" next="40"/>
<route src="10" dst="14" next="43"/>
<route src="10" dst="15" next="43"/>
<route src="11" dst="0" next="44"/>
<route src="11" dst="1" next="44"/>
<route src="11" dst="2" next="44"/>
<route src="11" dst="3" next="45"/>
<route src="11" dst="4" next="44"/>
<route src="11" dst="5" next="44"/>
<route src="11" dst="6" next="44"/>
<route src="11" dst="7" next="45"/>
<route src="11" dst="8" next="44"/>
<route src="11" dst="9" next="44"/>
<route src="11" dst="10" next="44"/>
<route src="11" dst="12" next="44"/>
<route src="11" dst="13" next="44"/>
<route src="11" dst="14" next="44"/>
<route src="11" dst="15" next="47"/>
<route src="12" dst="0" next="50"/>
<route src="12" dst="1" next="50"/>
<route src="12" dst="2" next="50"/>
<route src="12" dst="3" next="50"/>
<route src="12" dst="4" next="50"/>
<route src="12" dst="5" next="50"/>
<route src="12" dst="6" next="50"/>
<route src="12" dst="7" next="50"/>
<route src="12" dst="8" next="50"/>
<route src="12" dst="9" next="50"/>
<route src="12" dst="10" next="50"/>
<route src="12" dst="11" next="50"/>
<route src="12" dst="13" next="51"/>
<route src="12" dst="14" next="51"/>
<route src="12" dst="15" next="51"/>
<route src="13" dst="0" next="52"/>
<route src="13" dst="1" next="53"/>
<route src="13" dst="2" next="53"/>
<route src="13" dst="3" next="53"/>
<route src="13" dst="4" next="52"/>
<route src="13" dst="5" next="53"/>
<route src="13" dst="6" next="53"/>
<route src="13" dst="7" next="53"/>
<route src="13" dst="8" next="52"/>
<route src="13" dst="9" next="53"/>
<route src="13" dst="10" next="53"/>
<route src="13" dst="11" next="53"/>
<route src="13" dst="12" next="52"/>
<route src="13" dst="14" next="55"/>
<route src="13" dst="15" next="55"/>
<route src="14" dst="0" next="57"/>
<route src="14" dst="1" next="57"/>
<route src="14" dst="2" next="58"/>
<route src="14" dst="3" next="58"/>
<route src="14" dst="4" next="57"/>
<route src="14" dst="5" next="57"/>
<route src="14" dst="6" next="58"/>
<route src="14" dst="7" next="58"/>
<route src="14" dst="8" next="57"/>
<route src="14" dst="9" next="57"/>
<route src="14" dst="10" next="58"/>
<route src="14" dst="11" next="58"/>
<route src="14" dst="12" next="57"/>
<route src="14" dst="13" next="57"/>
<route src="14" dst="15" next="59"/>
<route src="15" dst="0" next="60"/>
<route src="15" dst="1" next="60"/>
<route src="15" dst="2" next="60"/>
<route src="15" dst="3" next="62"/>
<route src="15" dst="4" next="60"/>
<route src="15" dst="5" next="60"/>
<route src="15" dst="6" next="60"/>
<route src="15" dst="7" next="62"/>
<route src="15" dst="8" next="60"/>
<route src="15" dst="9" next="60"/>
<route src="15" dst="10" next="60"/>
<route src="15" dst="11" next="62"/>
<route src="15" dst="12" next="60"/>
<route src="15" dst="13" next="60"/>
<route src="15" dst="14" next="60"/>
<cpuroute dst="0" next="0"/>
<cpuroute dst="1" next="0"/>
<cpuroute dst="2" next="13"/>
<cpuroute dst="3" next="13"/>
<cpuroute dst="4" next="0"/>
<cpuroute dst="5" next="0"/>
<cpuroute dst="6" next="13"/>
<cpuroute dst="7" next="13"/>
<cpuroute dst="8" next="48"/>
<cpuroute dst="9" next="48"/>
<cpuroute dst="10" next="63"/>
<cpuroute dst="11" next="63"/>
<cpuroute dst="12" next="48"/>
<cpuroute dst="13" next="48"/>
<cpuroute dst="14" next="63"/>
<cpuroute dst="15" next="63"/>
</memroutes>
</memtopology>

**Comment by yuchaocs** [comment]
Please use the updated topology samples.
